# coding:utf-8
strr = """
 (1062, "Duplicate entry '蜜雪冰城项目从大风厂采购了4袋水泥-f782d741bf2d50' for key '87ace325f8855f8c9d72e8fd05ea2eb4.87ace325f8855f8c9d72e8fd05ea2eb4_ff254e55600153a29968d6f_0024291'") Traceback (most recent call last):||  File "/usr/local/lib/python3.8/site-packages/peewee_async.py", line 1463, in _run_sql||    await cursor.execute(operation, *args, **kwargs)||  File "/usr/local/lib/python3.8/site-packages/aiomysql/cursors.py", line 239, in execute||    await self._query(query)||  File "/usr/local/lib/python3.8/site-packages/aiomysql/cursors.py", line 457, in _query||    await conn.query(q)||  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 469, in query||    await self._read_query_result(unbuffered=unbuffered)||  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 672, in _read_query_result||    await result.read()||  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 1153, in read||    first_packet = await self.connection._read_packet()||  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 641, in _read_packet||    packet.raise_for_error()||  File "/usr/local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error||    err.raise_mysql_exception(self._data)||  File "/usr/local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception||    raise errorclass(errno, errval)||pymysql.err.IntegrityError: (1062, "Duplicate entry '蜜雪冰城项目从大风厂采购了4袋水泥-f782d741bf2d50' for key '87ace325f8855f8c9d72e8fd05ea2eb4.87ace325f8855f8c9d72e8fd05ea2eb4_ff254e55600153a29968d6f_0024291'")||||During handling of the above exception, another exception occurred:||||Traceback (most recent call last):||  File "/usr/local/lib/python3.8/site-packages/lemon_rag/api/base.py", line 100, in handle_all_api||    res = handler(request)||  File "/usr/local/lib/python3.8/site-packages/lemon_rag/api/base.py", line 48, in inner||    res = func(request)||  File "/usr/local/lib/python3.8/site-packages/lemon_rag/api/base.py", line 63, in inner||    res = func(structured_req)||  File "/usr/local/lib/python3.8/site-packages/lemon_rag/api/business.py", line 364, in save_receivable_payable_bill||    receivable_payable = receivable_payable_save_event(receivable_payable_bill, get_user())||  File "/usr/local/lib/python3.8/site-packages/lemon_rag/utils/business_save_utils.py", line 383, in receivable_payable_save_event||    rp = business_data_access.create_receivable_payable(receivable_payable_bill, project, employee, contract, creator)||  File "/usr/local/lib/python3.8/site-packages/lemon_rag/dependencies/data_access.py", line 1009, in create_receivable_payable||    return models.ReceivablePayableTab.create(**receivable_payable_data)||  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 6281, in create||    inst.save(force_insert=True)||  File "/root/back/apps/base_entity.py", line 1761, in save||    pk = self.insert(||  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 1877, in inner||    return method(self, database, *args, **kwargs)||  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 1948, in execute||    return self._execute(database)||  File "/root/back/apps/peewee_ext.py", line 368, in _execute||    result = sync_exector(self, self._main_loop_)||  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 223, in __call__||    return call_result.result()||  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result||    return self.__get_result()||  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result||    raise self._exception||  File "/usr/local/lib/python3.8/site-packages/asgiref/sync.py", line 292, in main_wrap||    result = await self.awaitable(*args, **kwargs)||  File "/root/back/runtime/modelapi/entity_utils.py", line 622, in submit_execute||    result = future.result()||  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 444, in result||    return self.__get_result()||  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result||    raise self._exception||  File "/root/back/apps/base_entity.py", line 3532, in execute||    result = (await coroutine(query))||  File "/usr/local/lib/python3.8/site-packages/peewee_async.py", line 594, in insert||    cursor = await _execute_query_async(query)||  File "/usr/local/lib/python3.8/site-packages/peewee_async.py", line 1480, in _execute_query_async||    return (await _run_sql(database, *query.sql()))||  File "/usr/local/lib/python3.8/site-packages/peewee_async.py", line 1468, in _run_sql||    return cursor||  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 2864, in __exit__||    reraise(new_type, new_type(exc_value, *exc_args), traceback)||  File "/usr/local/lib/python3.8/site-packages/peewee.py", line 183, in reraise||    raise value.with_traceback(tb)||  File "/usr/local/lib/python3.8/site-packages/peewee_async.py", line 1463, in _run_sql||    await cursor.execute(operation, *args, **kwargs)||  File "/usr/local/lib/python3.8/site-packages/aiomysql/cursors.py", line 239, in execute||    await self._query(query)||  File "/usr/local/lib/python3.8/site-packages/aiomysql/cursors.py", line 457, in _query||    await conn.query(q)||  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 469, in query||    await self._read_query_result(unbuffered=unbuffered)||  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 672, in _read_query_result||    await result.read()||  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 1153, in read||    first_packet = await self.connection._read_packet()||  File "/usr/local/lib/python3.8/site-packages/aiomysql/connection.py", line 641, in _read_packet||    packet.raise_for_error()||  File "/usr/local/lib/python3.8/site-packages/pymysql/protocol.py", line 221, in raise_for_error||    err.raise_mysql_exception(self._data)||  File "/usr/local/lib/python3.8/site-packages/pymysql/err.py", line 143, in raise_mysql_exception||    raise errorclass(errno, errval)||peewee.IntegrityError: (1062, "Duplicate entry '蜜雪冰城项目从大风厂采购了4袋水泥-f782d741bf2d50' for key '87ace325f8855f8c9d72e8fd05ea2eb4.87ace325f8855f8c9d72e8fd05ea2eb4_ff254e55600153a29968d6f_0024291'")|| rid=c2d846f1b3f648cf8936d9a526674a90 user_id=None
"""
print(strr.replace("||", "\n"))